ORG 0000H
SETB P1.0;FOR SENSOR 1
SETB P1.1;FOR SENSOR 2
MOV R0,#00;FOR ENTRY COUNT
MOV R1,#00;FOR EXIT COUNT
MOV TMOD,#05H;TMOD REGISTER CONFIGURED FOR FALLING EDGE DETECT
MOV IE,#85H;IE REGISTER CONFIGURED FOR INT1 AND INT0 ENABLE
MOV IP,#01H; IP REGISTER CONFIGURED FOR INT 1 PRIORITY(ENTRY PRIORITY

;ISR 1
ORG 0003H


;ISR 2
